sudo: false

language: go

services:
  - mysql

before_script:
  - cp config.json.example config.json
  - mysql -e 'CREATE DATABASE IF NOT EXISTS example;'
  - mysql example < db/table.sql

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - tip

script:
  - go test -v ./...
